- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible #equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 20HR
    TRAINER: Devi
  tasks:
  - name: print the course information
    ansible.builtin.debug:
    #Vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Duration: {{ DURATION }}, Trainer is {{TRAINER }}"

  - name: print the course information
    ansible.builtin.debug:
    #Vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Duration: {{ DURATION }}, Trainer is {{TRAINER }}"