- name: variables in arguments
  hosts: local
  connection: local
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"
      