- name: understand vars prefernces
  hosts: local
  connection: local
  var:
    GREETING: "Hello from PLAY"
  var_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: please enter the greeting 
    private: true
  tasks:
  - name: print the greeting 
    vars:
      GREETING: "Hello from TASK"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"      