- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.dubug:
      msg: "Hello, {{ item }}" #item here is reserved keyword
    loop:
    - Devi
    - Sudheer
    - Bhargavi
    - Yamini  